# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - elemenusappservicecompse

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://elemnusregistry.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_15a16409edb446b08ede1d4344abf541 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_47723a1dbb0b49ee82e0b027c81bcc12 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: elemnusregistry.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_15a16409edb446b08ede1d4344abf541 }}/elemenus-compose:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'elemenusappservicecompse'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_c38109edd2f9487f812de6b31c2d512b }}
        images: 'elemnusregistry.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_15a16409edb446b08ede1d4344abf541 }}/elemenus-compose:${{ github.sha }}'